from datetime import datetime

def generate_markdown(analysis: dict) -> str:
    """Generate a full markdown audit report from analysis results."""
    
    fname = analysis.get("filename", "unknown")
    score_data = analysis.get("score", {})
    parse = analysis.get("parse", {})
    security = analysis.get("security", [])
    bugs = analysis.get("bugs", [])
    ner = analysis.get("ner", [])
    doc = analysis.get("documentation", {})
    rag_refs = analysis.get("rag_references", {})
    
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    report = f"""# SentinAI Security Audit Report

**File:** `{fname}`  
**Generated:** {now}  
**Language:** {parse.get("language", "unknown").capitalize()}

---

## Code Health Score

| Metric | Value |
|--------|-------|
| Score | **{score_data.get("score", 0)}/100** |
| Grade | **{score_data.get("grade", "N/A")}** |
| Status | **{score_data.get("status", "Unknown")}** |
| Lines of Code | {score_data.get("lines_of_code", 0)} |
| Functions | {score_data.get("functions_count", 0)} |
| Critical Issues | {score_data.get("critical_issues", 0)} |
| High Issues | {score_data.get("high_issues", 0)} |
| Total Vulnerabilities | {score_data.get("total_vulnerabilities", 0)} |
| Total Bugs | {score_data.get("total_bugs", 0)} |
| Secrets Detected | {score_data.get("total_secrets", 0)} |

---

## Code Summary

{doc.get("summary", "No summary available.")}

**Purpose:** {doc.get("purpose", "N/A")}

---

## Security Vulnerabilities ({len(security)})

"""
    
    if security:
        for i, v in enumerate(security, 1):
            refs = rag_refs.get(v["vulnerability"], [])
            ref_text = ""
            if refs:
                ref_text = "\n  **References:**\n"
                for r in refs:
                    ref_text += f"  - [{r.get('id', 'N/A')}] {r.get('name', '')}: {r.get('remediation', '')}\n"
            
            report += f"""### {i}. {v["vulnerability"]} — `{v["severity"]}`

- **Line:** {v["line"]}
- **CWE:** {v.get("cwe", "N/A")}
- **Code:** `{v["snippet"]}`
- **Description:** {v["description"]}
{ref_text}
---
"""
    else:
        report += "_No security vulnerabilities detected._\n\n---\n"
    
    report += f"\n## Bugs & Code Quality Issues ({len(bugs)})\n\n"
    
    if bugs:
        for i, b in enumerate(bugs, 1):
            report += f"""### {i}. {b["bug"]} — `{b["severity"]}`

- **Line:** {b["line"]}
- **Code:** `{b["snippet"]}`
- **Description:** {b["description"]}

---
"""
    else:
        report += "_No bugs detected._\n\n---\n"
    
    report += f"\n## Sensitive Entities Detected ({len(ner)})\n\n"
    
    if ner:
        for entity in ner:
            report += f"- **Line {entity['line']}** [{entity['severity']}] `{entity['type']}`: `{entity['snippet']}`\n"
    else:
        report += "_No sensitive entities detected._\n"
    
    report += f"\n---\n\n## Auto-Generated Documentation\n\n"
    report += doc.get("readme_section", "_Documentation unavailable._")
    
    funcs_doc = doc.get("functions_doc", {})
    if funcs_doc:
        report += "\n\n### Function Descriptions\n\n"
        for fn, desc in funcs_doc.items():
            report += f"- **`{fn}()`**: {desc}\n"
    
    report += f"\n\n---\n*Report generated by SentinAI | {now}*\n"
    
    return report